'use strict';
window.ChickenProteinView=(()=>{
 const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
 const fmt=v=>v===null||v===undefined?'Sin captura':new Intl.NumberFormat('es-MX',{maximumFractionDigits:3}).format(v);
 const time=v=>v?new Date(v).toLocaleString('es-MX',{timeZone:'America/Mexico_City'}):'Sin registro';
 const names={rosti:'Rostizado',cruji:'Crujiente'},slots={morning:'Mañana',noon:'Mediodía',other:'Otra entrega'};
 function cards(d){return `<div class="protein-cards">${d.rows.map(r=>`<section class="protein-card"><h3>${r.name}</h3><p class="protein-total">${fmt(r.total)} <span>pollos que quedan en CEDIS</span></p><dl><dt>Sin marinar en CEDIS</dt><dd>${fmt(r.raw.current)}</dd><dt>Pollos Marinados en CEDIS</dt><dd>${fmt(r.marinated.current)}</dd></dl><p class="protein-hint">Ambas cantidades siguen en CEDIS. Los pollos enviados a Sucursal ya no van aquí.</p><dl><dt>Llegaron del proveedor hoy (+)</dt><dd>${fmt(r.entries)}</dd><dt>Se marinaron hoy (siguen en CEDIS)</dt><dd>${fmt(r.prepared)}</dd><dt>Salieron a Sucursal hoy (−)</dt><dd>${fmt(r.sent)}</dd><dt>Sucursal confirmó que recibió</dt><dd>${fmt(r.received)}</dd><dt>Se perdieron o dañaron hoy (−)</dt><dd>${fmt(r.waste)}</dd>${r.adjustment?`<dt>Corrección de cantidades hoy</dt><dd>${r.adjustment>0?'+':''}${fmt(r.adjustment)}</dd>`:''}</dl>${r.correction?`<p class="protein-verification"><strong>Inventario rectificado el ${esc(r.correction.date)}</strong><br>Sin marinar: ${fmt(r.correction.before.raw)} → ${fmt(r.correction.after.raw)}<br>Pollos Marinados: ${fmt(r.correction.before.marinated)} → ${fmt(r.correction.after.marinated)}<br>${esc(r.correction.actor)} · ${esc(time(r.correction.at))}<br>${esc(r.correction.notes)}</p>`:''}${verification(r)}</section>`).join('')}</div>`;}
 function verification(r){return ['raw','marinated'].map(key=>{
  const c=r[key].count,label=key==='raw'?'Sin marinar':'Pollos Marinados';
  return c?`<p class="protein-verification ${c.difference!==0?'protein-warning':''}"><strong>${label}: conteo ${fmt(c.quantity)} · diferencia ${c.difference>0?'+':''}${fmt(c.difference)}</strong><br>${esc(c.actor)} · ${esc(time(c.at))}<br>${esc(c.notes)}${c.movedSince?'<br>Hubo movimientos después del conteo.':''}</p>`:`<p class="protein-hint">${label}: sin conteo físico.</p>`;
 }).join('');}
 function shipments(d){return `<p class="${d.pending?'protein-warning':''}">${d.pending} envíos pendientes de confirmar${d.shipments.some(s=>s.receipt?.difference)?' · Hay diferencias en recepciones.':'.'}</p><div class="protein-scroll"><table><caption>Envíos y confirmaciones hasta ${esc(d.date)} · pollos</caption><thead><tr><th>Fecha / entrega</th><th>Proteína</th><th>Enviado</th><th>Recibido</th><th>Diferencia</th><th>Entregó / recibió</th></tr></thead><tbody>${d.shipments.slice().reverse().map(s=>`<tr><td>${esc(s.date)}<br>${slots[s.slot]||''}</td><td>${names[s.protein]}</td><td>${fmt(s.sent)}</td><td>${s.receipt?fmt(s.receipt.amount):'Pendiente'}</td><td class="${s.receipt?.difference?'protein-warning':''}">${s.receipt?fmt(s.receipt.difference):'Pendiente'}</td><td>${esc(s.actor)} · ${esc(time(s.at))}<br>${s.receipt?esc(s.receipt.actor)+' · '+esc(time(s.receipt.at)):'Recepción pendiente'}<br>${esc(s.receipt?.notes||s.notes)}</td></tr>`).join('')||'<tr><td colspan="6">Sin envíos registrados.</td></tr>'}</tbody></table></div>`;}
 function week(d){return d.rows.map(product=>{
  const rows=d.week.filter(w=>w.rows).map(w=>w.rows.find(r=>r.protein===product.protein));
  const sum=key=>Math.round(rows.reduce((n,r)=>n+r[key],0)*1000)/1000;
  return `<h3>${product.name}</h3><div class="protein-scroll"><table><caption>Semana del ${esc(d.week[0].date)} · pollos</caption><thead><tr><th>Día</th><th>Había sin marinar</th><th>Había marinado</th><th>Llegó proveedor (+)</th><th>Se marinaron</th><th>Salieron (−)</th><th>Sucursal recibió</th><th>Pérdidas (−)</th><th>Rectificación (+/−)</th><th>Quedan sin marinar</th><th>Quedan marinados</th><th>Quedan en CEDIS</th></tr></thead><tbody>${d.week.map(w=>{
   const r=w.rows?.find(r=>r.protein===product.protein);
   return `<tr><th>${esc(new Date(w.date+'T12:00:00Z').toLocaleDateString('es-MX',{weekday:'short',day:'numeric',month:'short',timeZone:'UTC'}))}</th>${r?[r.raw.previous,r.marinated.previous,r.entries,r.prepared,r.sent,r.received,r.waste,r.adjustment??0,r.raw.current,r.marinated.current,r.total].map(n=>`<td>${fmt(n)}</td>`).join(''):'<td colspan="11">Posterior a la fecha consultada</td>'}</tr>`;
  }).join('')}</tbody><tfoot><tr><th>Acumulado hasta ${esc(d.date)}</th><td>—</td><td>—</td>${['entries','prepared','sent','received','waste','adjustment'].map(k=>`<td>${fmt(sum(k))}</td>`).join('')}<td>${fmt(product.raw.current)}</td><td>${fmt(product.marinated.current)}</td><td>${fmt(product.total)}</td></tr></tfoot></table></div>`;
 }).join('')+'<p class="protein-hint">Las entradas y salidas se acumulan; las últimas tres columnas muestran la existencia al día consultado. No se suman existencias entre días.</p>';}
 function history(d){const labels={initial:'Primera captura',entry:'Llegó del proveedor (+)',marinate:'Se marinó',send:'Salió a Sucursal (−)',receive:'Sucursal recibió',count:'Conteo para comparar',waste:'Pérdida (−)',rectify:'RECTIFICACIÓN DE INVENTARIO'};
  return `<div class="protein-scroll"><table><thead><tr><th>Fecha</th><th>Proteína / estado</th><th>Qué se registró</th><th>Pollos</th><th>Quién / cuándo</th><th>Comentario</th></tr></thead><tbody>${d.history.map(e=>`<tr><td>${esc(e.date)}</td><td>${names[e.protein]}<br>${e.state==='raw'?'Sin marinar':'Pollos Marinados'}</td><td>${labels[e.action]||esc(e.kind)}${e.action==='marinate'?(e.kind==='exit'?' · se restó sin marinar':' · se sumó marinado'):''}</td><td>${e.action==='rectify'?`${fmt(e.before?.[e.state])} → ${fmt(e.after?.[e.state])}`:fmt(e.quantity)}</td><td>${esc(e.actor)}<br>${esc(time(e.at))}</td><td>${esc(e.notes)}</td></tr>`).join('')||'<tr><td colspan="6">Sin movimientos esta semana.</td></tr>'}</tbody></table></div>`;}
 return {esc,fmt,cards,shipments,week,history,names,slots};
})();
